//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionAlumno
    {
        public int miClave { get; set; }
        public Nullable<short> Id_A { get; set; }
        public Nullable<short> ID_M { get; set; }
        public Nullable<decimal> calif_1 { get; set; }
        public Nullable<decimal> calif_2 { get; set; }
        public Nullable<decimal> calif_3 { get; set; }
        public Nullable<decimal> calif_4 { get; set; }
        public Nullable<decimal> calif_f { get; set; }
        public Nullable<short> ano { get; set; }
        public Nullable<byte> Periodo { get; set; }
    }
}
