//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public short ID_M { get; set; }
        public string Nombre_Materia { get; set; }
        public Nullable<short> id_c { get; set; }
        public Nullable<byte> cuatrimestre { get; set; }
    
        public virtual Carrera Carrera { get; set; }
    }
}
