//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor()
        {
            this.profesor1 = new HashSet<profesor>();
        }
    
        public short Id_p { get; set; }
        public string nombre_prof { get; set; }
        public string app_prof { get; set; }
        public string apm_prof { get; set; }
        public Nullable<byte> edad_prof { get; set; }
        public string sexo_prof { get; set; }
        public Nullable<short> Id_jefe { get; set; }
        public Nullable<short> id_c { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesor> profesor1 { get; set; }
        public virtual profesor profesor2 { get; set; }
    }
}
